### ISSUE TITLE
Streamline build process

### ISSUE THREAD

**Issue by Henrik0x7F** [net64-mod/net64-coop#38]
The cmake script should be able to build a fully functional executable + environment:
- [x] Use windeployqt to bundle necessary Qt environment (#40)
    - [x] A similar mechanism for Linux would be nice
- [x] Add option to include a Mupen64Plus binary dir with the installation (#40)
    - [x] Use gitmodule to automatically pull a binary depending on OS / architecture (#42)
- [ ] Use CPack to create a Windows installer
    - [ ] Find a way to update the Windows build
- [x] Add option to build an [AppImage](https://docs.appimage.org/packaging-guide/index.html) (Linux)
    - [ ] Add portable Linux binary build mode ([Forcing lower glibc version](https://stackoverflow.com/questions/4032373/linking-against-an-old-version-of-libc-to-provide-greater-application-coverage))
    -  ~~Dynamically switch between bundled and native Qt libs~~
    - [ ] Add updater via appimageupdate

**Comment by Henrik0x7F** [comment]
On bundling Qt libs and using CPack: 
https://blog.nathanosman.com/2017/11/24/using-windeployqt-with-cpack.html
